# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.17.11
# Mod Properties
mod_id=pridetags
mod_version=2.0.0
mod_name=Pride Tags
maven_group=uk.co.finleyofthewoods
archives_base_name=PrideTags
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.152.1+26.1.2
lombok_version=1.18.46